# Generated by Django 3.2.7 on 2021-10-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_telegramuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_admin',
        ),
    ]
