# Generated by Django 3.2.7 on 2021-10-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_telegramuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Администратор'),
        ),
    ]
