# Generated by Django 3.2.7 on 2021-10-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_telegramuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
