version: '3.9'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    restart: always
    container_name: volodya_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    env_file:
      - .env

  backend:
    build: .
    restart: always
    container_name: volodya_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - .:/app
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    build: ./nginx
    restart: always
    container_name: volodya_nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8000:80
    depends_on:
      - backend