# Generated by Django 3.2.7 on 2021-09-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.FileField(upload_to='voices', verbose_name='Голосовое сообщение')),
            ],
            options={
                'verbose_name': 'Голосовое сообщение',
                'verbose_name_plural': 'Голосовые сообщения',
            },
        ),
    ]
