# Generated by Django 3.2.7 on 2021-09-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voicemessage',
            options={'ordering': ['id'], 'verbose_name': 'Голосовое сообщение', 'verbose_name_plural': 'Голосовые сообщения'},
        ),
    ]
