# Generated by Django 3.2.7 on 2021-09-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_voicemessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker', models.FileField(upload_to='media/stickers', verbose_name='Стикеры')),
            ],
            options={
                'verbose_name': 'Стикер',
                'verbose_name_plural': 'Стикеры',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='voicemessage',
            name='voice',
            field=models.FileField(upload_to='media/voices', verbose_name='Голосовое сообщение'),
        ),
    ]
