# Generated by Django 3.2.7 on 2021-09-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210907_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwearWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='Ругательное слово')),
            ],
            options={
                'verbose_name': 'Ругательное слово',
                'verbose_name_plural': 'Ругательные слова',
                'ordering': ['id'],
            },
        ),
    ]
