# Generated by Django 3.2.7 on 2021-12-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_telegramuser_is_admin'),
        ('bot', '0005_swearword'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayGreeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(max_length=50, verbose_name='Название праздника')),
                ('text', models.TextField(verbose_name='Текст поздравления')),
                ('send_on', models.DateTimeField(verbose_name='Дата отправки')),
                ('users', models.ManyToManyField(related_name='holiday_greetings', to='users.TelegramUser', verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Поздравление с праздниками',
                'verbose_name_plural': 'Поздравления с праздниками',
                'ordering': ['id'],
            },
        ),
    ]
