name: volodya-ci

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Tests
      run: pytest
      env:
        SECRET_KEY: ${{ secret.SECRET_KEY }}
        DEBUG: ${{ secret.DEBUG }}
        ALLOWED_HOSTS: ${{ secret.ALLOWED_HOSTS }}
        DB_NAME: ${{ secret.DB_NAME }}
        DB_USER: ${{ secret.DB_USER }}
        DB_HOST: ${{ secret.DB_HOST }}
        DB_PORT: ${{ secret.DB_PORT }}
        DB_PASSWORD: ${{ secret.DB_PASSWORD }}
        BOT_TOKEN: ${{ secret.BOT_TOKEN }}
        EMAIL_HOST: ${{ secret.EMAIL_HOST }}
        EMAIL_HOST_USER: ${{ secret.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secret.EMAIL_HOST_PASSWORD }}
        EMAIL_PORT: ${{ secret.EMAIL_PORT }}
        EMAIL_USE_TLS: ${{ secret.EMAIL_USE_TLS }}
        WEATHER_API_TOKEN: ${{ secret.WEATHER_API_TOKEN }}