#name: volodya-ci
#
#on: [push]
#
#jobs:
#  tests:
#    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres
#        ports:
#          - 5432:5432
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.9
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#
#    - name: Tests
#      run: pytest
#      env:
#        SECRET_KEY: ${{ secrets.SECRET_KEY }}
#        DEBUG: ${{ secrets.DEBUG }}
#        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
#        DB_NAME: ${{ secrets.DB_NAME }}
#        DB_USER: ${{ secrets.DB_USER }}
#        DB_HOST: ${{ secrets.DB_HOST }}
#        DB_PORT: ${{ secrets.DB_PORT }}
#        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
#        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
#        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
#        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
#        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
#        EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
#        WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN }}